### ISSUE TITLE
TCPConnectWrap ECONNREFUSED 

### ISSUE THREAD

**Issue by Noah-Schoonover** [Asaye/MyDriverDemo#1]
I downloaded the zip and tried to run with `node App`. I was met with the following error:

`Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306
}`

I also tried port 3000. Does there need to be a server open to listen for requests from App.js? I am new to node so I apologize if this is elementary.

**Comment by Noah-Schoonover** [comment]
I fixed this issue with a little random trial and error. The solution was to open an http-server in another terminal on port 8080, and then set the `const config` port in App.js to 8080. 

When I ran `node App` again, I received "Connection successful". 

I am aware that this is probably basic understanding for most, but it might be beneficial to add that you have to have a server listening to your article. (which is excellent by the way 👍)

**Comment by Asaye** [comment]
Hi, the error can arise due to various reasons. Try to look for possible solutions on www.stackoverflow.com.

    On Friday, November 6, 2020, 1:31:00 PM GMT+3, Noah Schoonover <notifications@github.com> wrote:  
 
 


Closed #1.

**Comment by Asaye** [comment]
Thank you for the suggestion.
    On Friday, November 6, 2020, 01:29:09 PM GMT+3, Noah Schoonover <notifications@github.com> wrote:  
 
 


I fixed this issue with a little random trial and error. The solution was to open an http-server in another terminal on port 8080, and then set the const config port in App.js to 8080.

When I ran node App again, I received "Connection successful".

I am aware that this is probably basic understanding for most, but it might be beneficial to add that you have to have a server listening to your article. (which is excellent by the way 👍 )
