### ISSUE TITLE
Error in _authenticate

### ISSUE THREAD

**Issue by Ankizle** [Asaye/MyDriverDemo#2]
Hello, I am trying to test this project, but when running the following commands I'm getting an error in the _authenticate method.

```
git clone https://github.com/Asaye/MyDriverDemo.git
cd MyDriverDemo
node App
```

This is the full log I get when running the code.
```
Connection successful!
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "byteLength" argument must be of type number. Received undefined
    at validateNumber (internal/validators.js:125:11)
    at boundsError (internal/buffer.js:70:5)
    at Buffer.readUIntLE (internal/buffer.js:175:3)
    at MyDriver._authenticate (C:\Users\me\Programming\TestMySQL\MyDriverDemo\MyDriver.js:73:23)
    at Socket.<anonymous> (C:\Users\me\Programming\TestMySQL\MyDriverDemo\MyDriver.js:49:19)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

From what I can tell, this error is happening because of the usage of `readUIntLE`. I looked into the documentation, and found that it requires 2 arguments, the offset, which you have given, and the byteLength, which was not given. Is there a way to fix this?

**Comment by Ankizle** [comment]
I did a bit of testing, and tried to call the `readUIntLE` with different `byteLengths`. The documentation tells us that it must be 1 <= byteLength <= 6. If I passed a second argument, .which was between 1 and 6, this was the log:

```
Connection successful!
error occurred during query.
```

I am assuming this is because changing the `_authenticate ` method would prevent access to the database.

**Comment by Asaye** [comment]
Sorry for not responding earlier. In this case, the error occurs during query and you need to check if your SQL command has some errors.
    On Saturday, November 21, 2020, 11:25:20 PM GMT+3, Ankizle <notifications@github.com> wrote:  
 
 


I did a bit of testing, and tried to call the readUIntLE with different byteLengths. The documentation tells us that it must be 1 <= byteLength <= 6. If I passed a second argument, .which was between 1 and 6, this was the log:
Connection successful!
error occurred during query.

I am assuming this is because changing the _authenticate  method would prevent access to the database.

**Comment by Ankizle** [comment]
Thank you for the reply! You were correct in that the query had an issue in it. I did not change the query from what you gave, and my database did not have the `customers` table. In the _authenticate method, I added the second argument to `readUIntLE` to be 1, and the query worked! Thank you for your help.
